### ISSUE TITLE
Uber Issue: Deliverables for May 7th for Wieniek 

### ISSUE THREAD

**Issue by abhandary** [SocialLocationReminder/GoTeam#29]
1. When user search for a location on the map and taps on the location annotation icon, user is given the ability to save the location to the list of locations.
2. If the location already exists in the lists, user will be instead given an option to edit the location. 
3. User will be given the ability to tap on a spot in the map and then add the tapped spot to the list of locations.

**Comment by wieniek** [comment]
Features added and tested on May 7.
