### ISSUE TITLE
Deliverables for KG

### ISSUE THREAD

**Issue by abhandary** [SocialLocationReminder/GoTeam#4]
1. User can create a Label
2. See the list of created labels
3. Edit a created label
4. Delete label
5. Search label
6. Able to tag tasks to created label(Strech goal ?)
7. Toggle list view : Group by Label, Date(Today, Tomorrow, This Week, This Month)

**Comment by karpagaganesh** [comment]
Checked in the code for 1-5 use cases. I am working on the remaining two stretch goals. But won't be submitting them this week. So if its alright, I will close this issue, as I have separate issues created for each of these use cases.
